### ISSUE TITLE
focuspointfiled doesnt' exist? 

### ISSUE THREAD

**Issue by sparkcom** [jonom/silverstripe-focuspoint#54]
in CMS's asset manager, when i click on an image, i got ' Injector.get(): Component FocusPointField does not exist'  on the right column.

**Comment by sparkcom** [comment]
ah, it's because the  resources/jonom web folder not accessible

**Comment by bummzack** [comment]
`composer vendor-expose` should fix that

**Comment by ChrissiQ** [comment]
I am having this problem in SilverStripe 4.3 with version 3.0 of this module.  `composer vendor-expose` does not fix it - the dist js/css files are loading fine.

This is the error appearing in the browser console:
```
vendor.js?m=1557111467:1 Error: Injector.get(): Component FocusPointField does not exist
    at Object.get (bundle.js?m=1557111467:1)
    at Object.get (bundle.js?m=1557111467:1)
    at t.value (bundle.js?m=1557111467:1)
    at bundle.js?m=1557111467:1
    at Array.map (<anonymous>)
    at t.value (bundle.js?m=1557111467:1)
    at bundle.js?m=1557111467:1
    at Array.map (<anonymous>)
    at t.value (bundle.js?m=1557111467:1)
    at bundle.js?m=1557111467:1
Rn @ vendor.js?m=1557111467:1
Un.n.callback @ vendor.js?m=1557111467:1
$t @ vendor.js?m=1557111467:1
Kt @ vendor.js?m=1557111467:1
yr @ vendor.js?m=1557111467:1
_r @ vendor.js?m=1557111467:1
hr @ vendor.js?m=1557111467:1
dr @ vendor.js?m=1557111467:1
rr @ vendor.js?m=1557111467:1
enqueueSetState @ vendor.js?m=1557111467:1
i.setState @ vendor.js?m=1557111467:1
c.onStateChange @ vendor.js?m=1557111467:1
notify @ vendor.js?m=1557111467:1
e.notifyNestedSubs @ vendor.js?m=1557111467:1
c.onStateChange @ vendor.js?m=1557111467:1
notify @ vendor.js?m=1557111467:1
e.notifyNestedSubs @ vendor.js?m=1557111467:1
c.onStateChange @ vendor.js?m=1557111467:1
notify @ vendor.js?m=1557111467:1
e.notifyNestedSubs @ vendor.js?m=1557111467:1
c.onStateChange @ vendor.js?m=1557111467:1
notify @ vendor.js?m=1557111467:1
e.notifyNestedSubs @ vendor.js?m=1557111467:1
c.onStateChange @ vendor.js?m=1557111467:1
notify @ vendor.js?m=1557111467:1
e.notifyNestedSubs @ vendor.js?m=1557111467:1
c.onStateChange @ vendor.js?m=1557111467:1
notify @ vendor.js?m=1557111467:1
e.notifyNestedSubs @ vendor.js?m=1557111467:1
c.onStateChange @ vendor.js?m=1557111467:1
u @ vendor.js?m=1557111467:1
(anonymous) @ vendor.js?m=1557111467:1
(anonymous) @ vendor.js?m=1557111467:1
(anonymous) @ bundle.js?m=1557111467:1
Promise.then (async)
value @ bundle.js?m=1557111467:1
value @ bundle.js?m=1557111467:1
yr @ vendor.js?m=1557111467:1
_r @ vendor.js?m=1557111467:1
hr @ vendor.js?m=1557111467:1
jr @ vendor.js?m=1557111467:1
Re @ vendor.js?m=1557111467:1
```

**Comment by azt3k** [comment]
Have filed a pull request for this issue https://github.com/jonom/silverstripe-focuspoint/pull/62
